postgresql:
  image: jcalazan/postgresql
  environment:
    - POSTGRESQL_DB=youtubeadl
    - POSTGRESQL_USER=youtubeadl
    - POSTGRESQL_PASSWORD=password
  volumes:
    - ~/dockerfiles/youtube-audio-dl/postgresql:/var/lib/postgresql
  ports:
    - "5432:5432"

rabbitmq:
  image: jcalazan/rabbitmq
  ports:
    - "15672:15672"

# NOTES:
#   - The C_FORCE_ROOT variable allows celery to run as the root user.
celery:
  image: jcalazan/django
  environment:
    - C_FORCE_ROOT=true
    - DATABASE_HOST=postgresql
    - BROKER_URL=amqp://guest:guest@rabbitmq//
  working_dir: /youtube-audio-dl
  command: bash -c "sleep 3 && celery -A youtubeadl worker -E -l info --concurrency=3"
  volumes:
    - ~/dockerfiles/youtube-audio-dl/python:/usr/local/lib/python2.7
    - ~/dockerfiles/youtube-audio-dl/bin:/usr/local/bin
    - ../youtube-audio-dl:/youtube-audio-dl
  links:
    - postgresql
    - rabbitmq

# NOTES:
#   - The C_FORCE_ROOT variable allows celery to run as the root user.
flower:
  image: jcalazan/django
  environment:
    - C_FORCE_ROOT=true
    - DATABASE_HOST=postgresql
    - BROKER_URL=amqp://guest:guest@rabbitmq//
  working_dir: /youtube-audio-dl
  command: bash -c "sleep 3 && celery -A youtubeadl flower --port=5555"
  volumes:
    - ~/dockerfiles/youtube-audio-dl/python:/usr/local/lib/python2.7
    - ~/dockerfiles/youtube-audio-dl/bin:/usr/local/bin
    - ../youtube-audio-dl:/youtube-audio-dl
  ports:
    - "5555:5555"
  links:
    - postgresql
    - rabbitmq

django:
  image: jcalazan/django
  environment:
    - DATABASE_HOST=postgresql
    - BROKER_URL=amqp://guest:guest@rabbitmq//
  working_dir: /youtube-audio-dl
  command: bash -c "sleep 3 && python manage.py runserver_plus 0.0.0.0:80" 
  volumes:
    - ~/dockerfiles/youtube-audio-dl/python:/usr/local/lib/python2.7
    - ~/dockerfiles/youtube-audio-dl/bin:/usr/local/bin
    - ../youtube-audio-dl:/youtube-audio-dl
  ports:
    - "80:80"
  links:
    - postgresql
    - rabbitmq