---

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml

- include: setup_git_repo.yml
  tags: deploy

- include: setup_django_app.yml
  tags: deploy

- include: setup_supervisor.yml

- include: set_file_permissions.yml
  tags: deploy

- include: setup_nginx.yml